#spring.application.name=meals-app
logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      google:
        firebase:
          auth: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meals-app
    username: root
    password: Aman_859821
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
