#spring.application.name=meals-app

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meals-app
    username: root
    password: Aman_859821
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
